# -*- coding: utf-8 -*-
"""python.programming-2024.july.08-module01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQOUXOvWbpFGqGKpdrazqPg9ukKRGaL8
"""

age = 51

print(type(age))



print(age)

name = "jack bauer"

type(name)

money = 12536.42

type(money)

is_old = age > 50



type(is_old)

print(is_old)

is_old = True

is_old = False

type(is_old)

salary = None

type(salary)

type(None)

type(False)

type(age > 50)

type(2 + 2. * 2)

type(2)

type(2.0)

type(4 / 2)

type(4 // 2)

5 / 2

5 // 2

x = 42

x = "jack bauer"

x = 2+2 == 4

print(type(x))

x = 5 / 2

print(type(x))

x = float("inf")

x = float("NaN")

print(x)

x = float("-inf")

print(x)

x = float("NaN")

x = x + 1

print(x)

x = x * 0

print(x)

y = 42

y == 42

x == float("nan")

x == x

import math

math.isnan(x)

x = float("-inf")

math.isinf(x)

x = 42

math.isfinite(x)

money = 2.0
money = money - 1.10
print(money)

x = (0.1 + 0.2) + 0.3

y = 0.1 + (0.2 + 0.3)

x == y

0.1 + 0.2

type(0.1 + 0.2)

z = 100 * 4.35

print(z)

pi = 4 * math.atan(1)
print(pi)

from mpmath import *

mp.dps = 100_000
mp.pretty = True

mp_pi = 4 * atan(1)

print(mp_pi)

x = 4.33

math.ceil(x)

math.floor(x)

round(x)

x = 4.78

round(x)

x = 2 ** 10

print(x)

type(x)

x = 2 ** 100_000

int("42")

print(type("42"))
print(type(int("42")))

int(4.9999)

int("42")

float("inf")

float("3.141516")

float("nan")

bool("sdfsdf")

fullname = "kate austen" # str: immutable

print(type(fullname))

print(fullname)

print(len(fullname))

fullname.upper()

fullname

fullname.capitalize()

fullname

fullname.replace('e','a')

fullname

x = "\u20ba"

x

x = b"\xf0\x9d\x84\x9e"

type(x)

print(x)

y = x.decode("utf-8")

print(y)

type(y)

print(y)

len(y)

z = "x"

len(z)

# collation -> müller mueller

name1 = "müller"

name2 = "mueller"

name1 == name2

jack = """
{
  "name": {
    "first_name": "jack",
    "last_name": "bauer"
  },
  "salary": {
    "value": 100000,
    "currency": "TL"
  }
}
"""